
run:
  deadline: 1m

linters:
  enable-all: true
  disable:
    - gosimple
    - gocyclo
    - gochecknoinits
    - golint
    - gochecknoglobals
    - dupl
    - interfacer
    - gosec
    - unparam
    - lll
    - maligned
    - nakedret
    - errcheck
    - scopelint
    - prealloc
    - varcheck

linters-settings:
  govet:
    check-shadowing: true
issues:
  exclude:
    - composites