env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  main: ./cli.go
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
brews:
  - tap:
      owner: Miloas
      name: homebrew-tv
    folder: Formula
    homepage:  https://github.com/Miloas/tv
    description: Tag version cli
    test: |
      system "#{bin}/tv", "help"
