env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ldflags:
     - -X main.tvVersion=$(git describe --tags)
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
brews:
  - github:
      owner: Miloas
      name: homebrew-tv
    folder: Formula
    homepage:  https://github.com/Miloas/tv
    description: tag version cli
    test: |
      system "#{bin}/tv help"
